# Generated by Django 5.0 on 2023-12-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('currency', models.TextField()),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2024)),
                ('month', models.CharField(max_length=255, null=True)),
                ('category', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_in_month', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_in_year', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2024)),
                ('month', models.CharField(max_length=255)),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('income_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('income_uah', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('single_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ssc', models.DecimalField(decimal_places=2, default=1474.0, max_digits=10)),
                ('total_taxes', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('clean_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('additional_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_left', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
