# Generated by Django 5.0 on 2024-01-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrule',
            name='fixed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='taxrule',
            name='tax_type',
            field=models.CharField(choices=[('PER', 'Percentage'), ('FIX', 'Fixed Amount')], default='PER', max_length=3),
        ),
        migrations.AddField(
            model_name='transfer',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='taxrule',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
